### PR TITLE
[Feature] Compare

### PR DESCRIPTION
**Pull request by TheRolfFR**
## Full compare working compare request
image

## Arguments
With 3 arguments and 2 first required:
- ``<search>`` the search sentence
- ``[<--resolution|--res|--r>=]<16j|32j|64j|16b|32b|64b>`` The resolution wanted
And one optional
- ``[<--scale|--s>=<1..10>]`` for the compare result image scale

long arguments (--) need = when short ones (-) need space :
--scale=<scale> --s=<scale>
-scale <scale> -s <scale>
Achieved with [getops](https://www.npmjs.com/package/getopts) module.

You can repeat the resolution argument to compare even more texture, between multiple editions.

## Result
Normal
image
You can even chain the resolutions:
image
And by adding result chaining the results to my script, resolution word is optional (not intended):
image

## Request
To respond to noice #69 issue

### CODE REVIEW

**Review by Juknum — APPROVED** [review]

**Comment by RobertRR11** [comment]
I think it would be better to have a "=" instead of spaces for the arguments, to have more consistency with the other commands, everything else looks good

**Comment by Juknum** [comment]
> I think it would be better to have a "=" instead of spaces for the arguments, to have more consistency with the other commands, everything else looks good

we can also replace all other commands to use this

**Comment by Juknum** [comment]
Small idea:
- Use a "not found" texture when no texture found.
- Use a default setup when no args are given
- Permit to compare more than 2 texture, (scalable command)

**Comment by Juknum** [comment]
For the "multiple" compare at once, draw x16 at left, then higher resolution. Like that, right/left parameters can be removed

**Review by Juknum — COMMENTED** [review]
see comments i've made :)

**Review by Juknum — CHANGES_REQUESTED** [review]
see comments i've made (for real xdd)

**Comment by Chromus-dev** [comment]
> I think it would be better to have a "=" instead of spaces for the arguments, to have more consistency with the other commands, everything else looks good

there is a great npm package for this called [getopts](https://www.npmjs.com/package/getopts) which gets all the options from the args so you could have both

**Comment by TheRolfFR** [comment]
> there is a great npm package for this called getopts which gets all the options from the args so you could have both

Thank you, this will be definitely be useful for me! It is a powerful tool I could use to parse more arguments

**Comment by Chromus-dev** [comment]
> > there is a great npm package for this called getopts which gets all the options from the args so you could have both
> 
> Thank you, this will be definitely be useful for me! It is a powerful tool I could use to parse more arguments

np! i use it all the time

**Review by RobertRR11 — APPROVED** [review]

**Review by Juknum — APPROVED** [review]

**Pull request merged**
