### PR TITLE
[Bug fix] Solved your blocked issue with Mutexes

### PR DESCRIPTION
**Pull request by TheRolfFR**
Hello,
The solution to your problem is the mutex.
Basically, it's a lock, allowing you to safely access a shared resource (here a file).
You acquire the lock, act on your resource, and then you release it so that others can use it.
More infos if you are curious : https://www.youtube.com/watch?v=9lAuS6jsDgE

This is will solve your concurrency problems : #38

### CODE REVIEW

**Review by RobertRR11 — CHANGES_REQUESTED** [review]
removing contributors doesn't seem to work anymore
image

**Comment by TheRolfFR** [comment]
> removing contributors doesn't seem to work anymore
why would the add work but not the remove ? It's the same thing.

> the bot isn't locked, but it just doesn't work
Does it still crashes ? What happens ? Is it blocked somewhere ?

**Comment by RobertRR11** [comment]
Literally nothing happens when trying to remove a contributor. No crashes, no errors, no logs, nothing at all.

**Comment by TheRolfFR** [comment]
So You opened resources you didn't use so you set the lock that's why it is not working. I rewrote entirely contributors to handle the mutex

**Review by RobertRR11 — APPROVED** [review]

**Pull request merged**
