### PR TITLE
Fix for voided JSON?

### PR DESCRIPTION
**Pull request by TheRolfFR**
So I just clone the JSON repo at start, not very clean but does the job perfectly

### CODE REVIEW

**Comment by Juknum** [comment]
If the bot does not send his JSON files when stopped, it could cause desync issues? (lost data)
Might be better to use another system than local files? 👀
like fetch json repo each time a json is required, then push it. (Might cause spam with the moderation.json which is updated each 30s)

**Review by Juknum — CHANGES_REQUESTED** [review]
If the bot does not send his JSON files when stopped, it could cause desync issues? (lost data)
Might be better to use another system than local files? 👀
like fetch json repo each time a json is required, then push it. (Might cause spam with the moderation.json which is updated each 30s)

**Comment by TheRolfFR** [comment]
> If the bot does not send his JSON files when stopped

You think you know when the bot stops? No, that is the problem, you don't. I thought you pushed to github to avoid these kind of problems.

> Might be better to use another system than local files? 👀

Yes it would be better because we already had some problems with files (fileHandler...) and we keep getting some problems. A lightweight real database should be the way to go. You could use replit database system ([link](https://docs.replit.com/misc/database)) or host it externally

**Comment by RobertRR11** [comment]
We won't use the replit database, because I'm going to host the bot myself soon.

**Comment by Juknum** [comment]
this pull request has been overcome by #71

**Pull request closed without merging**
